name: Calculator Tests

on:
  push:
  workflow_dispatch:

jobs:
  check-deadline:
    name: Check deadline & commit limit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check restrictions
        uses: dismath-coursework/testing-module-action@main
        with:
          mode: check
          internal-token: ${{ secrets.TESTSUITE_INTERNAL_TOKEN }}

  test-all:
    name: Run all tests
    needs: check-deadline
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run hidden test suite
        uses: dismath-coursework/testing-module-action@main
        with:
          mode: test

          alphabet: "a,b,d,f,i,k,g,j,h,e,c"

          minimum: "aa"
          maximum: "cc"

          student-source-dir: src

          internal-token: ${{ secrets.TESTSUITE_INTERNAL_TOKEN }}